import { Mesh } from 'three';

export class Resource {
    readonly name:               string;
    readonly color:              number;
    readonly total:              number;    // kg (natural deposit; Number.MAX_SAFE_INTEGER for manufactured)
    readonly gatherAmount:       number;    // kg per manual tap
    readonly isFuel:             boolean;
    readonly energyDensityMJkg:  number;   // MJ/kg lower heating value (0 for non-fuels)
    readonly isManufactured:     boolean;  // true = no pad on map; produced by structures
    readonly unit:               string;   // 'kg' for most resources, 'kWh' for Electricity
    gathered = 0;                           // held amount in `unit` units
    mesh:    Mesh | null = null;
    hitMesh: Mesh | null = null;

    constructor(
        name:              string,
        color:             number,
        total:             number,
        gatherAmount:      number,
        isFuel             = false,
        energyDensityMJkg  = 0,
        isManufactured     = false,
        unit               = 'kg',
    ) {
        this.name              = name;
        this.color             = color;
        this.total             = total;
        this.gatherAmount      = gatherAmount;
        this.isFuel            = isFuel;
        this.energyDensityMJkg = energyDensityMJkg;
        this.isManufactured    = isManufactured;
        this.unit              = unit;
    }

    // amount defaults to one manual tap; pass a specific kg for truck loads
    gather(amount = this.gatherAmount): boolean {
        if (this.gathered >= this.total) return false;
        this.gathered = Math.min(this.total, this.gathered + amount);
        return true;
    }

    // Add manufactured/refined output — no deposit cap
    deposit(amount: number): void {
        this.gathered += amount;
    }

    consume(kg: number): boolean {
        if (this.gathered < kg) return false;
        this.gathered -= kg;
        return true;
    }

    get hex(): string {
        return '#' + this.color.toString(16).padStart(6, '0');
    }

    get displayAmount(): string {
        const n = this.gathered;
        if (this.unit === 'kWh') {
            if (n >= 1_000_000_000) return `${(n / 1_000_000_000).toFixed(2)} TWh`;
            if (n >= 1_000_000)     return `${(n / 1_000_000).toFixed(2)} GWh`;
            if (n >= 1_000)         return `${(n / 1_000).toFixed(1)} MWh`;
            return `${n.toFixed(0)} kWh`;
        }
        if (n >= 1_000_000_000_000) return `${(n / 1_000_000_000_000).toFixed(2)} Gt`;
        if (n >= 1_000_000_000)     return `${(n / 1_000_000_000).toFixed(2)} Mt`;
        if (n >= 1_000_000)         return `${(n / 1_000_000).toFixed(2)} kt`;
        if (n >= 1_000)             return `${(n / 1_000).toFixed(1)} t`;
        return `${n} kg`;
    }
}

const SAVE_KEY = 'gather_inventory_v1';

export function saveInventory(resources: Resource[]): void {
    const data: Record<string, number> = {};
    for (const r of resources) data[r.name] = r.gathered;
    localStorage.setItem(SAVE_KEY, JSON.stringify(data));
}

export function loadInventory(resources: Resource[]): void {
    try {
        const raw = localStorage.getItem(SAVE_KEY);
        if (!raw) return;
        const data = JSON.parse(raw) as Record<string, number>;
        for (const r of resources) {
            const saved = data[r.name];
            if (typeof saved === 'number') r.gathered = Math.min(saved, r.total);
        }
    } catch { /* ignore malformed save */ }
}

//                                name       color      total(kg)            tap  isFuel  MJ/kg  mfg?   unit
export const RESOURCES: Resource[] = [
    new Resource('Wood',      0x8B5E3C, 1_000_000_000_000, 1_000, true,  15.0),         // dry hardwood LHV
    new Resource('Stone',     0x9E9E9E, 1_000_000_000_000, 1_000),
    new Resource('Iron',      0xB0BEC5, 1_000_000_000_000, 1_000),
    new Resource('Coal',      0x455A64, 1_000_000_000_000, 1_000, true,  24.0),         // bituminous coal LHV
    new Resource('Crystal',   0x00BCD4, 1_000_000_000_000, 1_000),
    new Resource('Steel',     0x90a4ae, Number.MAX_SAFE_INTEGER, 0, false,  0,    true),  // manufactured
    new Resource('Oil',       0x3e2723, 1_000_000_000_000, 0,   true,  42.7),          // crude oil LHV; hitMesh set by OilWell
    new Resource('Gasoline',  0xFFD700, Number.MAX_SAFE_INTEGER, 0, true, 44.5, true),  // refined petroleum; ~44.5 MJ/kg LHV
    new Resource('Electricity', 0xFDD835, Number.MAX_SAFE_INTEGER, 0, false, 0, true, 'kWh'), // generated by Power Plant
];
